site_name: Gradient
site_description: Nix-based Continuous Integration System
site_url: https://wavelens.github.io/gradient
repo_url: https://github.com/wavelens/gradient
repo_name: wavelens/gradient
copyright: Copyright &copy; 2026 Wavelens GmbH

theme:
  name: readthedocs

docs_dir: docs/src

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage:
    - Overview: usage/overview.md
    - CLI: usage/cli.md
    - API: usage/api.md
    - Pull Deployment: usage/pull-deployment.md
  - Development:
    - Architecture: development/architecture.md
    - Internals: development/internals.md
    - Proto: development/proto.md
    - Tests: development/tests.md
    - Contributing: development/contributing.md

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - fenced_code
