/*
 * SPDX-FileCopyrightText: 2026 Wavelens GmbH <info@wavelens.io>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

export const DARK_SHADOWS = {
  '--gr-shadow-raised': 'inset 0 1px 0 rgb(255 255 255 / 0.05)',
  '--gr-shadow-overlay': '0 8px 24px rgb(0 0 0 / 0.55), 0 0 0 1px rgb(255 255 255 / 0.07)',
  '--gr-shadow-modal': '0 20px 48px rgb(0 0 0 / 0.65), 0 0 0 1px rgb(255 255 255 / 0.09)',
} as const;

export const LIGHT_SHADOWS = {
  '--gr-shadow-raised': '0 1px 2px rgb(31 35 40 / 0.08)',
  '--gr-shadow-overlay': '0 8px 24px rgb(31 35 40 / 0.16)',
  '--gr-shadow-modal': '0 20px 48px rgb(31 35 40 / 0.24)',
} as const;

export const LINE_HEIGHTS = { tight: 1.25, base: 1.5, relaxed: 1.7 } as const;
export const CONTROL_HEIGHT_PX = 34;

export interface RoleDoc {
  name: string;
  usage: string;
}

/// Layer 1. Raw values, theme-independent. Components never reference these directly.
export const PALETTE: Record<string, string> = {
  '--gr-white': '#ffffff',
  '--gr-black': '#000000',
  '--gr-gray-950': '#050708',
  '--gr-gray-900': '#0d1118',
  '--gr-gray-870': '#161c24',
  '--gr-gray-800': '#232b35',
  '--gr-gray-775': '#2b343f',
  '--gr-gray-760': '#39434f',
  '--gr-gray-750': '#333d49',
  '--gr-gray-700': '#2d333b',
  '--gr-gray-650': '#5f6c80',
  '--gr-gray-400': '#818181',
  '--gr-gray-350': '#aab3bd',
  '--gr-gray-300': '#c2c9d1',
  '--gr-gray-200': '#d0d7de',
  '--gr-gray-250': '#7d8898',
  '--gr-gray-100': '#eaeef2',
  '--gr-gray-75': '#dde3ea',
  '--gr-gray-60': '#d1d9e2',
  '--gr-gray-50': '#e9edf2',
  '--gr-ink-900': '#1f2328',
  '--gr-slate-600': '#525a62',
  '--gr-slate-500': '#8c959f',
  '--gr-slate-550': '#5c646c',
  '--gr-green-800': '#115c26',
  '--gr-green-900': '#0f5323',
  '--gr-green-700': '#166c2e',
  '--gr-green-600': '#1a7f37',
  '--gr-green-550': '#23913d',
  '--gr-emerald-400': '#34d399',
  '--gr-emerald-500': '#10b981',
  '--gr-emerald-700': '#047857',
  '--gr-emerald-800': '#065f46',
  '--gr-green-500': '#28a745',
  '--gr-green-400': '#22c55e',
  '--gr-red-300': '#f87171',
  '--gr-red-700': '#a40e19',
  '--gr-red-900': '#8f1620',
  '--gr-red-600': '#cf222e',
  '--gr-red-550': '#bd2130',
  '--gr-red-500': '#dc3545',
  '--gr-red-400': '#ef4444',
  '--gr-amber-800': '#7d5300',
  '--gr-amber-900': '#6b4700',
  '--gr-amber-700': '#9a6700',
  '--gr-amber-550': '#e6ac06',
  '--gr-amber-500': '#ffc107',
  '--gr-orange-500': '#f97316',
  '--gr-cyan-500': '#17a2b8',
  '--gr-blue-600': '#0969da',
  '--gr-blue-900': '#064a9c',
  '--gr-blue-500': '#3b82f6',
  '--gr-purple-500': '#6f42c1',
};

/// Layer 2. Every value is a palette key, never a literal, so a theme is a pure remap.
export const DARK_ROLES: Record<string, string> = {
  '--gr-surface-sunken': '--gr-gray-950',
  '--gr-surface-base': '--gr-gray-900',
  '--gr-surface-raised': '--gr-gray-800',
  '--gr-surface-control': '--gr-gray-870',
  '--gr-surface-hover': '--gr-gray-775',
  '--gr-surface-active': '--gr-gray-750',
  '--gr-border': '--gr-gray-650',
  '--gr-border-subtle': '--gr-gray-760',
  '--gr-accent': '--gr-emerald-400',
  '--gr-accent-hover': '--gr-emerald-500',
  '--gr-accent-fg': '--gr-gray-900',
  '--gr-focus-ring': '--gr-white',
  '--gr-text-primary': '--gr-white',
  '--gr-text-secondary': '--gr-gray-300',
  '--gr-text-muted': '--gr-gray-350',
  '--gr-status-success': '--gr-green-500',
  '--gr-status-success-text': '--gr-green-500',
  '--gr-status-success-hover': '--gr-green-400',
  '--gr-status-success-fg': '--gr-black',
  '--gr-status-danger': '--gr-red-300',
  '--gr-status-danger-text': '--gr-red-300',
  '--gr-status-danger-hover': '--gr-red-400',
  '--gr-status-danger-fg': '--gr-black',
  '--gr-status-warning': '--gr-amber-500',
  '--gr-status-warning-text': '--gr-amber-500',
  '--gr-status-warning-hover': '--gr-amber-550',
  '--gr-status-warning-fg': '--gr-black',
  '--gr-status-info': '--gr-cyan-500',
  '--gr-status-info-text': '--gr-cyan-500',
  '--gr-graph-success': '--gr-green-400',
  '--gr-graph-danger': '--gr-red-400',
  '--gr-graph-warning': '--gr-orange-500',
  '--gr-graph-running': '--gr-blue-500',
};

export const LIGHT_ROLES: Record<string, string> = {
  '--gr-surface-sunken': '--gr-gray-100',
  '--gr-surface-base': '--gr-gray-50',
  '--gr-surface-raised': '--gr-white',
  '--gr-surface-control': '--gr-white',
  '--gr-surface-hover': '--gr-gray-75',
  '--gr-surface-active': '--gr-gray-60',
  '--gr-border': '--gr-gray-250',
  '--gr-border-subtle': '--gr-gray-60',
  '--gr-accent': '--gr-emerald-700',
  '--gr-accent-hover': '--gr-emerald-800',
  '--gr-accent-fg': '--gr-white',
  '--gr-focus-ring': '--gr-ink-900',
  '--gr-text-primary': '--gr-ink-900',
  '--gr-text-secondary': '--gr-slate-600',
  '--gr-text-muted': '--gr-slate-550',
  '--gr-status-success': '--gr-green-600',
  '--gr-status-success-text': '--gr-green-900',
  '--gr-status-success-hover': '--gr-green-700',
  '--gr-status-success-fg': '--gr-white',
  '--gr-status-danger': '--gr-red-600',
  '--gr-status-danger-text': '--gr-red-900',
  '--gr-status-danger-hover': '--gr-red-700',
  '--gr-status-danger-fg': '--gr-white',
  '--gr-status-warning': '--gr-amber-700',
  '--gr-status-warning-text': '--gr-amber-900',
  '--gr-status-warning-hover': '--gr-amber-800',
  '--gr-status-warning-fg': '--gr-white',
  '--gr-status-info': '--gr-blue-600',
  '--gr-status-info-text': '--gr-blue-900',
  '--gr-graph-success': '--gr-green-600',
  '--gr-graph-danger': '--gr-red-600',
  '--gr-graph-warning': '--gr-orange-500',
  '--gr-graph-running': '--gr-blue-600',
};

export const SEMANTIC_ROLES: readonly RoleDoc[] = [
  { name: '--gr-surface-sunken', usage: 'Page background behind raised cards' },
  { name: '--gr-surface-base', usage: 'Default page background' },
  { name: '--gr-surface-raised', usage: 'Cards, dialogs, popovers' },
  { name: '--gr-surface-control', usage: 'Form control fill, distinct from the card it sits in' },
  { name: '--gr-surface-hover', usage: 'Hover row and control backgrounds' },
  { name: '--gr-surface-active', usage: 'Pressed and active control backgrounds' },
  { name: '--gr-border-subtle', usage: 'Panel outlines and dividers' },
  { name: '--gr-border', usage: 'All borders and dividers' },
  { name: '--gr-accent', usage: 'Primary action colour: default buttons, checked controls, focus rings' },
  { name: '--gr-accent-hover', usage: 'Hover state for accent surfaces' },
  { name: '--gr-accent-fg', usage: 'Text and icons on an accent background' },
  { name: '--gr-focus-ring', usage: 'Keyboard focus ring, one colour for every control' },
  { name: '--gr-text-primary', usage: 'Body and heading text' },
  { name: '--gr-text-secondary', usage: 'Supporting text, meta rows, hints' },
  { name: '--gr-text-muted', usage: 'Disabled and placeholder text' },
  { name: '--gr-status-success-text', usage: 'Label on a tinted success badge or banner' },
  { name: '--gr-status-success', usage: 'Success badges, completed states' },
  { name: '--gr-status-success-hover', usage: 'Hover state for success surfaces' },
  { name: '--gr-status-success-fg', usage: 'Text and icons on a success background' },
  { name: '--gr-status-danger-text', usage: 'Label on a tinted danger badge or banner' },
  { name: '--gr-status-danger', usage: 'Errors, failed states, destructive actions' },
  { name: '--gr-status-danger-hover', usage: 'Hover state for destructive surfaces' },
  { name: '--gr-status-danger-fg', usage: 'Text and icons on a destructive background' },
  { name: '--gr-status-warning-text', usage: 'Label on a tinted warning badge or banner' },
  { name: '--gr-status-warning', usage: 'Warnings and degraded states' },
  { name: '--gr-status-warning-hover', usage: 'Hover state for warning surfaces' },
  { name: '--gr-status-warning-fg', usage: 'Text and icons on a warning background' },
  { name: '--gr-status-info-text', usage: 'Label on a tinted info badge or banner' },
  { name: '--gr-status-info', usage: 'Informational badges and links' },
  { name: '--gr-graph-success', usage: 'Chart series: successful builds' },
  { name: '--gr-graph-danger', usage: 'Chart series: failed builds' },
  { name: '--gr-graph-warning', usage: 'Chart series: warnings' },
  { name: '--gr-graph-running', usage: 'Chart series: running builds' },
] as const;

export function resolveRole(role: string, theme: 'dark' | 'light'): string {
  const roles = theme === 'dark' ? DARK_ROLES : LIGHT_ROLES;
  return PALETTE[roles[role]] ?? '';
}
