[package]
name = "gradient-server"
version = "0.1.0"
authors = ["Wavelens UG <info@wavelens.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-ssh2-lite = { version = "0.5", features = ["tokio"] }
axum = "0.7"
chrono = "0.4"
clap = { version = "4.5", features = ["derive", "env"] }
futures = "0.3"
nix-daemon = { git = "https://github.com/wavelens/nix-daemon", tag = "v0.1.2" }
sea-orm = { version = "1.1", features = ["json-array", "mock", "postgres-array", "runtime-tokio", "sqlx-postgres", "with-uuid"] }
sea-orm-migration = { version = "1.1", features = ["with-uuid", "with-chrono", "with-json", "sqlx-postgres", "sea-orm-cli", "runtime-tokio"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.42", features = ["process", "rt-multi-thread"] }
uuid = { version = "1.11", features = ["fast-rng", "macro-diagnostics", "v4"] }
serde_json = "1.0"
migration = { path = "../migration" }
entity = { path = "../entity" }
oauth2 = "4.4"
password-auth = { version = "1.0.0", features = ["argon2"] }
async-trait = "0.1"
thiserror = "2.0"
reqwest = { version = "0.12", features = ["json"] }
jsonwebtoken = "9.3"
rand = "0.8"
axum-streams = { version = "0.19", features = ["json"] }
async-stream = "0.3"
pkcs8 = "0.10"
crypter = "0.2"
base64 = "0.22"
ssh-key = { version = "0.6", features = ["ed25519"] }
git-url-parse = "0.4"
