/*
 * SPDX-FileCopyrightText: 2026 Wavelens GmbH <info@wavelens.io>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

//! These aliases are pervasive in older code. Keeping them is avoiding a mass rename of
//! 1000+ call sites.

use gradient_entity::*;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

pub use gradient_entity::team_user::TeamRole;
pub use gradient_entity::{STORE_DIR, StorePath};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListItem {
    pub id: Uuid,
    pub name: String,
    pub managed: bool,
}

pub type ListResponse = Vec<ListItem>;

pub type EAdminTask = admin_task::Entity;
pub type EApi = api::Entity;
pub type EAuditLog = audit_log::Entity;
pub type EBuildAttempt = build_attempt::Entity;
pub type EBuildJob = build_job::Entity;
pub type EBuildProduct = build_product::Entity;
pub type EBuildRequestBlob = build_request_blob::Entity;
pub type ECache = cache::Entity;
pub type ECacheMetric = cache_metric::Entity;
pub type ECacheRole = cache_role::Entity;
pub type ECachedPath = cached_path::Entity;
pub type ECacheUpstream = cache_upstream::Entity;
pub type ECacheInvitation = cache_invitation::Entity;
pub type ECacheSubscriptionRequest = cache_subscription_request::Entity;
pub type ECacheUser = cache_user::Entity;
pub type ECliDeviceAuthorization = cli_device_authorization::Entity;
pub type ECommit = commit::Entity;
pub type EDerivation = derivation::Entity;
pub type EDerivationBuild = derivation_build::Entity;
pub type EDerivationDependency = derivation_dependency::Entity;
pub type EDerivationInputSource = derivation_input_source::Entity;
pub type EDerivationFeature = derivation_feature::Entity;
pub type EDerivationMetric = derivation_metric::Entity;
pub type EDerivationOutput = derivation_output::Entity;
pub type ECachedPathSignature = cached_path_signature::Entity;
pub type EDebugInfo = debug_info::Entity;
pub type EEntryPoint = entry_point::Entity;
pub type EEntryPointDepCount = entry_point_dep_count::Entity;
pub type EEntryPointMessage = entry_point_message::Entity;
pub type EEvalCacheStore = eval_cache_store::Entity;
pub type EEvaluation = evaluation::Entity;
pub type EEvaluationFlakeInputOverride = evaluation_flake_input_override::Entity;
pub type EEvaluationInputUpdate = evaluation_input_update::Entity;
pub type EOpenPrState = open_pr_state::Entity;
pub type EPendingDelivery = pending_delivery::Entity;
pub type EEvaluationMessage = evaluation_message::Entity;
pub type EFeature = feature::Entity;
pub type EIntegration = integration::Entity;
pub type EProject = project::Entity;
pub type EProjectCache = project_cache::Entity;
pub type EProjectInvitation = project_invitation::Entity;
pub type EProjectUser = project_user::Entity;
pub type ETeam = team::Entity;
pub type ETeamUser = team_user::Entity;
pub type ETeamProject = team_project::Entity;
pub type ETeamCache = team_cache::Entity;
pub type ETeamInvitation = team_invitation::Entity;
pub type ETeamProjectRequest = team_project_request::Entity;
pub type ETeamCacheRequest = team_cache_request::Entity;
pub type ETeamWorker = team_worker::Entity;
pub type EProjectAccess = project_access::Entity;
pub type ECacheAccess = cache_access::Entity;
pub type ETask = task::Entity;
pub type ETaskAction = task_action::Entity;
pub type ETaskActionDelivery = task_action_delivery::Entity;
pub type EWebhook = webhook::Entity;
pub type EWebhookDelivery = webhook_delivery::Entity;
pub type ETaskFlakeInputOverride = task_flake_input_override::Entity;
pub type ETaskTrigger = task_trigger::Entity;
pub type ERole = role::Entity;
pub type ESession = session::Entity;
pub type EStorageMigration = storage_migration::Entity;
pub type EUploadSession = upload_session::Entity;
pub type EUser = user::Entity;
pub type EUserSshKey = user_ssh_key::Entity;
pub type EWorkerRegistration = worker_registration::Entity;

pub type MAdminTask = admin_task::Model;
pub type MApi = api::Model;
pub type MAuditLog = audit_log::Model;
pub type MBuildAttempt = build_attempt::Model;
pub type MBuildJob = build_job::Model;
pub type MBuildProduct = build_product::Model;
pub type MBuildRequestBlob = build_request_blob::Model;
pub type MCache = cache::Model;
pub type MCacheMetric = cache_metric::Model;
pub type MCacheRole = cache_role::Model;
pub type MCachedPath = cached_path::Model;
pub type MCacheUpstream = cache_upstream::Model;
pub type MCacheInvitation = cache_invitation::Model;
pub type MCacheSubscriptionRequest = cache_subscription_request::Model;
pub type MCacheUser = cache_user::Model;
pub type MCliDeviceAuthorization = cli_device_authorization::Model;
pub type MCommit = commit::Model;
pub type MDerivation = derivation::Model;
pub type MDerivationBuild = derivation_build::Model;
pub type MDerivationDependency = derivation_dependency::Model;
pub type MDerivationInputSource = derivation_input_source::Model;
pub type MDerivationFeature = derivation_feature::Model;
pub type MDerivationMetric = derivation_metric::Model;
pub type MDerivationOutput = derivation_output::Model;
pub type MCachedPathSignature = cached_path_signature::Model;
pub type MDebugInfo = debug_info::Model;
pub type MEntryPoint = entry_point::Model;
pub type MEntryPointDepCount = entry_point_dep_count::Model;
pub type MEntryPointMessage = entry_point_message::Model;
pub type MEvalCacheStore = eval_cache_store::Model;
pub type MEvaluation = evaluation::Model;
pub type MEvaluationFlakeInputOverride = evaluation_flake_input_override::Model;
pub type MEvaluationInputUpdate = evaluation_input_update::Model;
pub type MOpenPrState = open_pr_state::Model;
pub type MPendingDelivery = pending_delivery::Model;
pub type MEvaluationMessage = evaluation_message::Model;
pub type MEvaluationAttrCost = evaluation_attr_cost::Model;
pub type MEvaluationMetric = evaluation_metric::Model;
pub type MFlakeOutputNode = flake_output_node::Model;
pub type MFeature = feature::Model;
pub type MIntegration = integration::Model;
pub type MProject = project::Model;
pub type MProjectCache = project_cache::Model;
pub type MProjectInvitation = project_invitation::Model;
pub type MProjectUser = project_user::Model;
pub type MTeam = team::Model;
pub type MTeamUser = team_user::Model;
pub type MTeamProject = team_project::Model;
pub type MTeamCache = team_cache::Model;
pub type MTeamInvitation = team_invitation::Model;
pub type MTeamProjectRequest = team_project_request::Model;
pub type MTeamCacheRequest = team_cache_request::Model;
pub type MTeamWorker = team_worker::Model;
pub type MProjectAccess = project_access::Model;
pub type MCacheAccess = cache_access::Model;
pub type MTask = task::Model;
pub type MTaskAction = task_action::Model;
pub type MTaskActionDelivery = task_action_delivery::Model;
pub type MWebhook = webhook::Model;
pub type MWebhookDelivery = webhook_delivery::Model;
pub type MTaskFlakeInputOverride = task_flake_input_override::Model;
pub type MTaskTrigger = task_trigger::Model;
pub type MRole = role::Model;
pub type MSession = session::Model;
pub type MStorageMigration = storage_migration::Model;
pub type MUploadSession = upload_session::Model;
pub type MUser = user::Model;
pub type MUserSshKey = user_ssh_key::Model;
pub type MWorkerRegistration = worker_registration::Model;

pub type AAdminTask = admin_task::ActiveModel;
pub type AApi = api::ActiveModel;
pub type AAuditLog = audit_log::ActiveModel;
pub type ABuildJob = build_job::ActiveModel;
pub type ABuildProduct = build_product::ActiveModel;
pub type ABuildRequestBlob = build_request_blob::ActiveModel;
pub type ACache = cache::ActiveModel;
pub type ACacheMetric = cache_metric::ActiveModel;
pub type ACacheRole = cache_role::ActiveModel;
pub type ACachedPath = cached_path::ActiveModel;
pub type ACacheUpstream = cache_upstream::ActiveModel;
pub type ACacheInvitation = cache_invitation::ActiveModel;
pub type ACacheSubscriptionRequest = cache_subscription_request::ActiveModel;
pub type ACacheUser = cache_user::ActiveModel;
pub type ACliDeviceAuthorization = cli_device_authorization::ActiveModel;
pub type ACommit = commit::ActiveModel;
pub type ADerivation = derivation::ActiveModel;
pub type ADerivationBuild = derivation_build::ActiveModel;
pub type ADerivationDependency = derivation_dependency::ActiveModel;
pub type ADerivationInputSource = derivation_input_source::ActiveModel;
pub type ADerivationFeature = derivation_feature::ActiveModel;
pub type ADerivationMetric = derivation_metric::ActiveModel;
pub type ADerivationOutput = derivation_output::ActiveModel;
pub type ACachedPathSignature = cached_path_signature::ActiveModel;
pub type ADebugInfo = debug_info::ActiveModel;
pub type AEntryPoint = entry_point::ActiveModel;
pub type AEntryPointDepCount = entry_point_dep_count::ActiveModel;
pub type AEntryPointMessage = entry_point_message::ActiveModel;
pub type AEvalCacheStore = eval_cache_store::ActiveModel;
pub type AEvaluation = evaluation::ActiveModel;
pub type AEvaluationFlakeInputOverride = evaluation_flake_input_override::ActiveModel;
pub type AEvaluationInputUpdate = evaluation_input_update::ActiveModel;
pub type AOpenPrState = open_pr_state::ActiveModel;
pub type APendingDelivery = pending_delivery::ActiveModel;
pub type AEvaluationMessage = evaluation_message::ActiveModel;
pub type AEvaluationAttrCost = evaluation_attr_cost::ActiveModel;
pub type AEvaluationMetric = evaluation_metric::ActiveModel;
pub type AFlakeOutputNode = flake_output_node::ActiveModel;
pub type AFeature = feature::ActiveModel;
pub type AIntegration = integration::ActiveModel;
pub type AProject = project::ActiveModel;
pub type AProjectCache = project_cache::ActiveModel;
pub type AProjectInvitation = project_invitation::ActiveModel;
pub type AProjectUser = project_user::ActiveModel;
pub type ATeam = team::ActiveModel;
pub type ATeamUser = team_user::ActiveModel;
pub type ATeamProject = team_project::ActiveModel;
pub type ATeamCache = team_cache::ActiveModel;
pub type ATeamInvitation = team_invitation::ActiveModel;
pub type ATeamProjectRequest = team_project_request::ActiveModel;
pub type ATeamCacheRequest = team_cache_request::ActiveModel;
pub type ATeamWorker = team_worker::ActiveModel;
pub type ATask = task::ActiveModel;
pub type ATaskAction = task_action::ActiveModel;
pub type ATaskActionDelivery = task_action_delivery::ActiveModel;
pub type AWebhook = webhook::ActiveModel;
pub type AWebhookDelivery = webhook_delivery::ActiveModel;
pub type ATaskFlakeInputOverride = task_flake_input_override::ActiveModel;
pub type ATaskTrigger = task_trigger::ActiveModel;
pub type ARole = role::ActiveModel;
pub type ASession = session::ActiveModel;
pub type AStorageMigration = storage_migration::ActiveModel;
pub type AUploadSession = upload_session::ActiveModel;
pub type AUser = user::ActiveModel;
pub type AUserSshKey = user_ssh_key::ActiveModel;
pub type AWorkerRegistration = worker_registration::ActiveModel;

pub type CAdminTask = admin_task::Column;
pub type CApi = api::Column;
pub type CAuditLog = audit_log::Column;
pub type CBuildAttempt = build_attempt::Column;
pub type CBuildJob = build_job::Column;
pub type CBuildProduct = build_product::Column;
pub type CBuildRequestBlob = build_request_blob::Column;
pub type CCache = cache::Column;
pub type CCacheMetric = cache_metric::Column;
pub type CCacheRole = cache_role::Column;
pub type CCachedPath = cached_path::Column;
pub type CCacheUpstream = cache_upstream::Column;
pub type CCacheInvitation = cache_invitation::Column;
pub type CCacheSubscriptionRequest = cache_subscription_request::Column;
pub type CCacheUser = cache_user::Column;
pub type CCliDeviceAuthorization = cli_device_authorization::Column;
pub type CCommit = commit::Column;
pub type CDerivation = derivation::Column;
pub type CDerivationBuild = derivation_build::Column;
pub type CDerivationDependency = derivation_dependency::Column;
pub type CDerivationInputSource = derivation_input_source::Column;
pub type CDerivationFeature = derivation_feature::Column;
pub type CDerivationMetric = derivation_metric::Column;
pub type CDerivationOutput = derivation_output::Column;
pub type CCachedPathSignature = cached_path_signature::Column;
pub type CDebugInfo = debug_info::Column;
pub type CEntryPoint = entry_point::Column;
pub type CEntryPointDepCount = entry_point_dep_count::Column;
pub type CEntryPointMessage = entry_point_message::Column;
pub type CEvalCacheStore = eval_cache_store::Column;
pub type CEvaluation = evaluation::Column;
pub type CEvaluationFlakeInputOverride = evaluation_flake_input_override::Column;
pub type CEvaluationInputUpdate = evaluation_input_update::Column;
pub type COpenPrState = open_pr_state::Column;
pub type CPendingDelivery = pending_delivery::Column;
pub type CEvaluationMessage = evaluation_message::Column;
pub type CFeature = feature::Column;
pub type CIntegration = integration::Column;
pub type CProject = project::Column;
pub type CProjectCache = project_cache::Column;
pub type CProjectInvitation = project_invitation::Column;
pub type CProjectUser = project_user::Column;
pub type CTeam = team::Column;
pub type CTeamUser = team_user::Column;
pub type CTeamProject = team_project::Column;
pub type CTeamCache = team_cache::Column;
pub type CTeamInvitation = team_invitation::Column;
pub type CTeamProjectRequest = team_project_request::Column;
pub type CTeamCacheRequest = team_cache_request::Column;
pub type CTeamWorker = team_worker::Column;
pub type CProjectAccess = project_access::Column;
pub type CCacheAccess = cache_access::Column;
pub type CTask = task::Column;
pub type CTaskAction = task_action::Column;
pub type CTaskActionDelivery = task_action_delivery::Column;
pub type CWebhook = webhook::Column;
pub type CWebhookDelivery = webhook_delivery::Column;
pub type CTaskFlakeInputOverride = task_flake_input_override::Column;
pub type CTaskTrigger = task_trigger::Column;
pub type CRole = role::Column;
pub type CSession = session::Column;
pub type CStorageMigration = storage_migration::Column;
pub type CUploadSession = upload_session::Column;
pub type CUser = user::Column;
pub type CUserSshKey = user_ssh_key::Column;
pub type CWorkerRegistration = worker_registration::Column;

pub use admin_task::{AdminTaskKind, AdminTaskStatus};
pub use evaluation_message::MessageLevel;
