[package]
name = "connector"
version = "0.2.0"
edition = "2024"
publish = false
license = "AGPL-3.0"
authors = ["Wavelens UG <info@wavelens.io>"]

[lib]
name = "connector"
path = "src/lib.rs"

[dependencies]
futures = "0.3"
reqwest = { version = "0.12", features = ["json"] }
reqwest-streams = { version = "0.10", features=["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
