name: "Test"
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      matrix:
        test:
          - gradient-state
          - gradient-api
          - gradient-building
          # - gradient-frontend
          - gradient-mail
          - gradient-oidc
          - gradient-remote
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          max-jobs = 2
          cores = 2

    - name: Run test - ${{ matrix.test }}
      run: |
        nix build .#checks.x86_64-linux.${{ matrix.test }} --print-build-logs
      timeout-minutes: 45

